### ISSUE TITLE
MTIColorLookupFilter() doesn't work on iOS 13

### ISSUE THREAD

**Issue by userich** [MetalPetal/MetalPetal#115]
Hi, YuAo
It seems Lookup Filter doesn't work properly on iOS 13 devices.
I am getting:
Error Domain=MTKTextureLoaderErrorDomain Code=0 "Image decoding failed" UserInfo={NSLocalizedDescription=Image decoding failed, MTKTextureLoaderErrorKey=Image decoding failed}

I am using 512x512 png table image

Thank you for this library!

**Comment by YuAo** [comment]
It's a MTKTextureLoaderError, meaning `MTKTextureLoader` cannot load your image. Commonly because your image is broken or in a format that cannot be decoded by `MTKTextureLoader`. You can probably fix this by exporting the image using "Preview" app (File -> Export), and choose "PNG" format and "8 Bit / Channel" depth.
