### ISSUE TITLE
Custom init on CIFilter subclass

### ISSUE THREAD

**Issue by ibprojects** [MetalPetal/MetalPetal#156]
I am really enjoying learning how to use MetalPetal. Wonderful work.

When recording video, I noticed when using a custom CIFilter subclass init with parameters that only the first time it's used do those parameters get passed. Every other time it uses the default init().

I am using it in CamerViewController from the demo project.

in viewDidLoad() ...
```
        ciuFilter = MTICoreImageUnaryFilter()
        ciMetalFilter = CIFilterLumAdjust(lumMin: 0.2, lumMax: 1.0)   //custom CIFilter 
        ciuFilter?.filter = ciuFilter
```

Is the best way to avoid this just use a custom MTIFilter?

Thanks for your help and time,
Ian

**Comment by YuAo** [comment]
`MTICoreImageUnaryFilter` actually copies the `CIFilter` you provide (because you may want to render the output image in a different thread/queue, we want to make sure that the `CIFilter` is not modified in the render thread.) 

I think your custom `CIFilter`s need to follow the "Subclassing notes for CIFilters" to make the copy work. You may want to check that your input parameters are prefixed with "input".
> To subclass a filter you need to perform the following tasks:
>
> Declare properties for the filter’s input parameters. **You must prefix each input parameter name with input, such as inputImage**.
> Override the setDefaults method, if necessary. (It’s not necessary in this example because the input parameters are set values.)
> Override the outputImage method.

Ref: https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreImaging/ci_filer_recipes/ci_filter_recipes.html#//apple_ref/doc/uid/TP30001185-CH4-SW1

Another way of using `CIFilter`s in MetalPetal is to use the `MTICoreImageKernel` which accepts a block to filter `CIImage`s. However you have to make sure the code in that block is thread-safe.

**Comment by ibprojects** [comment]
@YuAo that was just what I needed, thank you. 

I was able to get it working by using

`@objc dynamic var inputLumMax` and pass the parameters in my subclass. 

Thanks again!
