### ISSUE TITLE
iOS 12.4 not working (with Swift Package Manager)

### ISSUE THREAD

**Issue by R3l0ad3d** [MetalPetal/MetalPetal#160]
I use this library for image filter . i have device iPhone 6s, OS version 12.4 . but this device create empty context . 
### Checklist
i create new project and apply colorLookup filter but its gonna crash for empty MTIContext 
### Expected behavior
i run on simuletor in 13.0 + then its work fine . but in your information this library can work ios 10.0+ .
my XCode version is 11.5.
thanks in advanced .

**Comment by YuAo** [comment]
I don't think the iOS 12 simulator supports Metal. The suggestion is to run the demo on a real device.

**Comment by R3l0ad3d** [comment]
i run real device iPhone 6s os version 12.4 . that device create empty MTIContext.

**Comment by YuAo** [comment]
What is the error it reports? Or can you provide a demo project? @R3l0ad3d

**Comment by R3l0ad3d** [comment]
[This is my test project](https://github.com/R3l0ad3d/MetalPetalTest) please check. 
Error

-  program_source:1429:10: fatal error: 'TargetConditionals.h' file not found

#include <TargetConditionals.h>

- Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Context is nil.

**Comment by YuAo** [comment]
Swift PM does not support precompiled metal shaders currently (Swift 5.2). So we have to compile the shader at runtime. However the on device shader compiler does not recognize the `<TargetConditionals.h>` header (which we use to decide if we are running on a simulator) prior to iOS 13.

This is fixed with bde5bd9, by replacing `#include <TargetConditionals.h>` with a `#define TARGET_OS_SIMULATOR ...`

**Comment by R3l0ad3d** [comment]
Thanks. Its working
