### ISSUE TITLE
Is there a reason to restrict subclassing objc classes ?

### ISSUE THREAD

**Issue by omarojo** [MetalPetal/MetalPetal#180]
Hello @YuAo 

I noticed in Merge https://github.com/MetalPetal/MetalPetal/pull/163 
You added ```Apply objc_subclassing_restricted attribute to objective-c classes. Except the MTIUnaryImageRenderingFilter```

Is there a specific reason for this ? 
In one of my projects I was subclassing MTIRenderPipelineKernel. But now I get an error unable to compile.

**Comment by YuAo** [comment]
Classes marked as `objc_subclassing_restricted` are not designed to be subclassed. It's unsafe to subclass these classes because the implementation detail may change in a future version and that may break your subclass's logic.

Can you describe your use case of subclassing `MTIRenderPipelineKernel`?

**Comment by koopero** [comment]
Hi @YuAo . I work with @omarojo on this project. Thanks for your wonderful framework!

Our use case for subclassing `MTIRenderPipelineKernel` is a bit of a workaround to add unsupported rendering features, specifically overriding `newKernelStateWithContext` to alter the blend parameters of `colorAttachmentDescriptor`. In doing so, we use the kernel to render effects with significant overdraw in the single draw call.

While this is not the ideal solution, it is a good compromise. To implement these blend parameters in `MetalPetal` would push the scope your project significantly.

We understand the risks of this approach, and are quite willing to maintain our code to keep up with framework changes. Perhaps subclassing could be restricted by a gentleman's agreement rather than being explicitly denied?

**Comment by koopero** [comment]
For reference, [here is the code](https://gist.github.com/koopero/246be1ea1a9f1b15ffab2d17e70e8a00) for our override.

**Comment by YuAo** [comment]
I think blending would be a nice-to-have tool. There's an other issue about using blending #173 

I'll consider adding blending support to the framework.  For now, I think it's ok to temporary remove the `objc_subclassing_restricted` on `MTIRenderPipelineKernel`.

Also, @koopero What do you think about "Programmable blending"? Can you use that instead?

**Comment by koopero** [comment]
@YuAo thanks for the consideration and the suggestion. I'll admit that I hadn't considered programmable blending, being more used to old school GL. I'll give it a try in this case and get back to you.

**Comment by YuAo** [comment]
Programmable blending is more powerful and easy to use, so MetalPetal does not come with the pipeline level blending support. One thing to notice, if you are building a cross platform app,  is that "programmable blending" is not supported on Intel Macs (yes, Apple Silicon Macs support "programmable blending"),

**Comment by koopero** [comment]
**Programmable blending**

Wow. That works amazingly well. This revelation made the issue obsolete.

Thanks again @YuAo  and great work.
