### ISSUE TITLE
Increased memory footprint using renderImage

### ISSUE THREAD

**Issue by gltdv** [MetalPetal/MetalPetal#183]
Hello,

Does `renderImage` internally cache texture (in a texture pool)? Calling this function noticeably increases memory footprint, any best known method to avoid such memory use?

Thanks.

**Comment by YuAo** [comment]
Yes. And you can call `MTIContex.reclaimResources()` after render. 

If you are rendering images in a tight loop, e.g. a `for` loop, you'll need to wait for each render or you may end up queuing too much job on the GPU.
```Swift
for .... {
    let image = filter.outputImage
    var cgImage: CGImage?
    let task = context.startTask(toCreate: &cgImage, from: image, sRGB: false)
    task.waitUntilCompleted()
    context.reclaimResources()
    ....
}


```

**Comment by gltdv** [comment]
Thanks much @YuAo.

This might be a feature request. To avoid starving GPU, is it better to create an async call that allows reclaim resource at complete?

**Comment by YuAo** [comment]
No, you do not need to wait for the GPU to reclaim resources. The `reclaimResources` call can be before the `waitUntilCompleted` call. They have the same effect. Because the GPU also tracks the usage of the resources.

And there is an optional asynchronous`completion` block parameter in the `startTask...` method.
