### ISSUE TITLE
Lack of precision in float values.

### ISSUE THREAD

**Issue by alyfreym** [MetalPetal/MetalPetal#203]
Hi. I am trying to implement a repeat filter using scaling.

Input image - 
![new_old](https://user-images.githubusercontent.com/29518174/94986524-f46e0f00-0578-11eb-9b94-06549dffc74d.jpg)

And result - 
![IMG_7751](https://user-images.githubusercontent.com/29518174/94986559-3e56f500-0579-11eb-83f3-0afa607dc54a.PNG)

The filter scales the texture using repetitions. And apply flip effect to smooth repetition

my shader code:

`
fragment float4 mtiScaleTileEffect(metalpetal::VertexOut vertexIn [[stage_in]],
                                   texture2d<float, access::sample> sourceTexture [[texture(0)]],
                                   sampler sourceSampler [[sampler(0)]],
                                   constant float & scale [[ buffer(0) ]])
{
    float2 uv = vertexIn.textureCoordinate;
    
    
    uv -= float2(0.5); // relative center logic
    uv  = float2x2(scale, 0.0, 0.0, scale) * uv; // scale
    uv += float2(0.5); // relative center logic

    const bool flipTX = int(abs(floor(uv.x))) % 2 == 1;
    const bool flipTY = int(abs(floor(uv.y))) % 2 == 1;
    
    uv.x = fmod(flipTX ? 1.0 - uv.x : uv.x, 1.0);
    uv.y = fmod(flipTY ? 1.0 - uv.y : uv.y, 1.0);
    
    if (uv.x < 0) {
        uv.x = 1.0 + uv.x;
    }

    if (uv.y < 0) {
        uv.y = 1.0 + uv.y;
    }

    float4 color = sourceTexture.sample(sourceSampler, uv);

    return color;
}`

If you look from above you can see black lines where the repetition starts.

This occurs with an input value of  `1.46`

If for example the input value `1.48`

![IMG_7752](https://user-images.githubusercontent.com/29518174/94986895-deae1900-057b-11eb-91c8-f49f99fa83b2.PNG)

Black lines disappear. Everything is going smoothly
I suppose it has something to do with accuracy float.  

Any help is appreciated.

Sorry for my English. I am hope for your help.

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
I don't think it is related to float precision. It looks like a problem of your algorithm. If you clamp the uv's x and y in the valid value range the issue should disappear.

```
......
// Add the following lines before sample.
uv.x = clamp(uv.x, 0.5/sourceTexture.get_width(), 1.0 - 0.5/sourceTexture.get_width());
uv.y = clamp(uv.y, 0.5/sourceTexture.get_height(), 1.0 - 0.5/sourceTexture.get_height());

float4 color = sourceTexture.sample(sourceSampler, uv);
.......
```

I think you failed to handle the case where uv is not in the valid value range due to scaling. This causes the sampler to sample beyond the image, so you get the dark pixels.

BTW, the valid range for uv is `x: [0.5/width, (width - 0.5)/width]`, `y: [0.5/height, (height - 0.5)/height]`, because the location of the first pixel in the image is `x: 0.5/width, y: 0.5/height` (the center coord of the pixel), the last pixel is at `x: (width - 0.5)/width, y: (height - 0.5)/height`

---

Actually you don't have to do this yourself. The metal sampler support the mirror-repeat address mode. You can create a MTIImage with the mirror-repeat sampler using `image.withSamplerDescriptor(MTISamplerDescriptor.defaultSamplerDescriptor(with: .mirrorRepeat))`.

Then all you have to do in the shader is scale-and-sample:
```
uv -= float2(0.5); // relative center logic
uv  = float2x2(scale, 0.0, 0.0, scale) * uv; // scale
uv += float2(0.5); // relative center logic   
float4 color = sourceTexture.sample(sourceSampler, uv);
```
