### ISSUE TITLE
Converting Rec. 2020 to Rec. 2020 PQ

### ISSUE THREAD

**Issue by latenitefilms** [MetalPetal/MetalPetal#346]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

I've just come across this repo - awesome work! It looks amazing!

I'm currently trying to re-create this function in Apple's Final Cut Pro using Metal:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/22286696/211822751-2ec6daad-4766-4165-956f-0d6f037d9ae2.png">

I basically want to convert **Rec. 2020** (SDR) data into **Rec. 2020 PQ** (HDR) data. Is this something that's possible with MetalPetal?

To be honest, I have no idea what's actually happening under the hood in Final Cut Pro.

Any insight/ideas would be HUGELY appreciated!

**Comment by YuAo** [comment]
I do not own a copy of Final Cut Pro. I have no idea as well. 

If you know what it does mathematically you can use `MTIVideoComposition` to apply a custom filter to your video to covert it to HDR. 

Be sure to set the `MTIContext`'s `workingPixelFormat` to a non-normalize format (for example: MTLPixelFormatRGBA16Float, MTLPixelFormatBGR10_XR) if you'd like to work with HDR content since the value of a pixel may be greater than one.

You should also set the `colorPrimaries`, `colorTransferFunction` and `colorYCbCrMatrix` of the `MTIVideoComposition` properly.

**Comment by latenitefilms** [comment]
Legend, thanks heaps! I'll investigate. Appreciate the advice!
