### ISSUE TITLE
LookUpFilters look awful using MetalPetal

### ISSUE THREAD

**Issue by GustasBr** [MetalPetal/MetalPetal#36]
Maybe I'm doing something wrong. Please check two images below. First image is made with GPUImage2 and the second with MetalPetal. Why the difference is so huge? 

![37992738_1983380375025714_294567110770688000_n](https://user-images.githubusercontent.com/18195248/43417645-3472dcb4-9444-11e8-86ea-dd82cd6d826a.jpg)
![38001483_1983380328359052_4186797406483906560_n](https://user-images.githubusercontent.com/18195248/43417646-349083a4-9444-11e8-8dbc-7538a7f0f715.jpg)

I was using THE SAME FILTER for both pictures.
Also, I tried BlendMode ColorLookup512x512 and simple Color Lookup.

`guard let image = UIImage(named: "IMG_1506.jpg") else { return }
        guard let cgImage = image.cgImage else { return }
        guard let image2 = UIImage(named: "lookup_GENIJUS.png") else { return }
        guard let cgImage1 = image2.cgImage else { return }
        
        
        let filter = MTIBlendFilter.init(blendMode: MTIBlendMode.colorLookup512x512)
        
        
        
        filter.inputBackgroundImage = MTIImage(cgImage: cgImage)
        filter.inputImage = MTIImage(cgImage: cgImage1)
        
        
        if let device = MTLCreateSystemDefaultDevice(),
            let outputImage = filter.outputImage {
            do {
                let context = try MTIContext(device: device)
                let filteredImage = try context.makeCGImage(from: outputImage)
                image1.image = UIImage(cgImage: filteredImage)
            } catch {
                print(error)
            }
        }`

**Comment by YuAo** [comment]
Try creating your MTIImage from CGImage with SRGB = false option.
Like `[[MTIImage alloc] initWithCGImage:[UIImage imageNamed:@"ColorLookup512"].CGImage options:@{MTKTextureLoaderOptionSRGB: @(NO)}];`

BTW, You can use `MTIColorLookupFilter` it is more suitable for color lookup than using a blend filter.

**Comment by YuAo** [comment]
If you do not specify the `MTKTextureLoaderOptionSRGB` option. `MTKTextureLoader` may load the image in to a sRGB texture, e.g. `MTLPixelFormatR8Unorm_sRGB`, when you read pixel value from a sRGB texture in shader, you'll get the color value in linear space. It is the "right" behavior, because color values should be calculated in linear space. However it looks like you have a lookup table designed to work for sRGB colors.
If you use core image in it's default options, you may get the same result as you do in MetalPetal.  By default, Core Image assumes that processing nodes are 128 bits-per-pixel, linear light, premultiplied RGBA floating-point values that use the GenericRGB color space.  https://developer.apple.com/documentation/coreimage/kcicontextworkingcolorspace?language=swift
