### ISSUE TITLE
CLAHE filter not working on older devices?

### ISSUE THREAD

**Issue by obs1dium** [MetalPetal/MetalPetal#61]
Hi,

I'm currently playing around with the CLAHE filter, plugged it into the camera part of the demo app, it's working nicely on a recent iPhone running iOS 12.
However, on older devices (iPad mini 2, still on iOS 10, and an iPhone 5s running 12.1.3) I'm hitting a runtime assertion.
In the resolveWithContext method in MTICLAHEFilter.m, the kernelState.histogramKernel property appears to be nil.
Backtracking to newKernelStateWithContext, the MPSImageHistogram allocation fails there.
When running a release build there's no runtime error, of course, and the filter isn't applied.
Please let me know if I can help you with any additional information.

**Comment by YuAo** [comment]
CLAHE is only supported on devices support MetalPerformanceShaders. You can query the device's support by calling `MPSSupportsMTLDevice` or `MTIContext.defaultMetalDeviceSupportsMPS`.

However CLAHE filter should report `MTIErrorMPSKernelNotSupported` instead of assertion failure. This is an issue and I'll fix that ASAP.

**Comment by obs1dium** [comment]
Of course, that would explain it! Thanks!

**Comment by YuAo** [comment]
Fixed https://github.com/MetalPetal/MetalPetal/commit/4cab6166556d75f59976dff137920453ff69c18a

**Comment by YuAo** [comment]
Here's an article about the implementation of the CLAHE filter.
https://github.com/YuAo/Accelerated-CLAHE

If you're interested. @obs1dium

**Comment by obs1dium** [comment]
Very interesting, thanks!
