### ISSUE TITLE
iPhone 5s GPU hang (IOAF code 3)

### ISSUE THREAD

**Issue by AA-BMDI** [MetalPetal/MetalPetal#64]
Trying to apply MetalPetal filters on a prerecorded video, works on every device tested except the iPhone 5s - When I run, I get this logged 

`Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)`

and nothing appears on the screen. 

I'm grabbing each frame of the video using a CADisplayLink. 
Here's my code.
the renderView I'm applying the image to is a MTIImageView
![screenshot 2019-02-15 at 16 03 32](https://user-images.githubusercontent.com/32365469/52868451-4b706780-313b-11e9-8265-e2bc7bcf4e0a.png)

Also, if anyone as a better idea for applying a metal petal filter to an AVPlayer video, I'm all ears.

**Comment by YuAo** [comment]
What is the MetalPetal version you are using? And what are the filters you use?

Can you attach a project/code that can reproduce this problem.

**Comment by donobono** [comment]
I experienced similar situation. I could fix this problem using kCVPixelFormatType_420YpCbCr8BiPlanarFullRange instead of kCVPixelFormatType_32BGRA. 
Actually I have no idea exact reason of this, I just compared the metalPetal sample and my project when camera is started. 

I tested metalPetal sample with kCVPixelFormatType_32BGRA, same error was occurred.

**Comment by YuAo** [comment]
I do not have an iPhone 5s at hand currently. Will investigate tomorrow.

**Comment by donobono** [comment]
I tested with iPad mini 2nd gen and iPad Air. There is no problem in iPhones and iPad Pro 12.9 inch device.

**Comment by YuAo** [comment]
Can you try to change the `_coreVideoTextureBridge` initialization part in `-[MTIContext initWithDevice:.....]` method to use `MTICVMetalTextureCache` only.

Change:
```
if (@available(iOS 11_0, macOS 10_11, *)) {
    _coreVideoTextureBridge = [[MTICVMetalTextureBridge alloc] initWithDevice:device];
} else {
    NSError *coreVideoTextureCacheError = nil;
    _coreVideoTextureBridge = [[MTICVMetalTextureCache alloc] initWithDevice:device cacheAttributes:nil textureAttributes:nil error:&coreVideoTextureCacheError];
    if (coreVideoTextureCacheError) {
        if (inOutError) {
            *inOutError = coreVideoTextureCacheError;
        }
        return nil;
    }
}
```

to

```
 NSError *coreVideoTextureCacheError = nil;
_coreVideoTextureBridge = [[MTICVMetalTextureCache alloc] initWithDevice:device cacheAttributes:nil textureAttributes:nil error:&coreVideoTextureCacheError];
if (coreVideoTextureCacheError) {
    if (inOutError) {
        *inOutError = coreVideoTextureCacheError;
    }
    return nil;
}
```

Then test and see if the problem still exists.

**Comment by donobono** [comment]
After changing, I tested. 
Unfortunately, the result is same. Still errors are occurred.

**Comment by AA-BMDI** [comment]
I tried @donobono 's solution of changing the Pixel Format and it worked. I'll try implement @YuAo solution to see if I can get that working. Cheers.

**Comment by YuAo** [comment]
@AA-BMDI  That is irrelevant... I tried the solution myself and it does not work. It seems the YCbCr texture upload is way faster than BGRA texture upload on some old devices. Investigating...

**Comment by YuAo** [comment]
@AA-BMDI @donobono 

After some investigation. It turns out that the cause of this issue is using `CVMetalTextureCahce` or `IOSurface` to bind a CVPixelBuffer with BGRA pixel format to GPU on old devices.

Create a normal metal texture then use `replaceRegion` to fill in the CVPixelBuffer's content is "ok". However this will render heavy CPU usage because the system needs to copy the image data to the metal texture.

Unfortunately, `CVMetalTextureCahce` and `IOSurface` are the only ways of binding a `CVPixelBuffer` to GPU without copying the buffer's contents.

Perhaps, there is a way to migrate this problem. You may want to stick with the YCbCr pixel format while I try to find a workaround.

**Comment by YuAo** [comment]
@AA-BMDI @donobono 

Added a workaround for this issue. https://github.com/MetalPetal/MetalPetal/commit/ef890162a9941534909f78a2f980a2df1b4e2a6e

The idea is to use a blit command encoder to copy the CoreVideo texture to another metal texture. Don't know why this can resolve the issue, however, this seems to be the cheapest (in performance) workaround.

This issue only happens on Apple A7 chips (iPhone 5s, iPad mini 2, iPad Air). I added a metal feature set support check to ensure the fix won't apply on well behaved devices.
