### ISSUE TITLE
How to share common functions between shaders

### ISSUE THREAD

**Issue by omarojo** [MetalPetal/MetalPetal#77]
I notice that some of your filters are wrapped inside namespaces
for example:
```
#include "MTIShaderLib.h"
using namespace metal;
namespace metalpetal{
   namespace clahe{
         . . . some frag functions . . .
         . . . several METAL_FUNC functions . . .
   }
}
```
*Question 1*
For my shaders, Should I make individual *myShader.metal* for each shader I make and each within it's own namespace? i.e metalpetal>myshaderNamespace, Does it really make a difference making a bunch of .metal files or just 1?  
`MTIFunctionDescriptor(name:, libraryURL:)` will look throughout all .metal/.metallib files and namespaces ?

*Question 2*
What is *METAL_FUNC* ? I searched online but I cant find anything about it.
is that needed so that non-fragment functions can be used by the main fragment functions?

*Question 3*
I have functions that do their own thing, like Noise, Random, etc... that may or may not be used by other Shaders. What is the suggested way to write these global functions so that they are accesible by shaders written in other .metal files and should they use the METAL_FUNC prefix ?

Thank you for keeping the library active ! is awesome.

**Comment by YuAo** [comment]
1. The namespace thing is optional. I just use it to avoid naming conflicts, mostly from the library users.  For example, it's totally fine if you'd like to define a function named `rotm`. Because the `rotm`in MetalPetal is in the metalpetal::halftone:: namespace. So it's not recommended for you to add anything to the metalpetal namespace, it's reserved for the library.
`MTIFunctionDescriptor(name:, libraryURL:)` ignores the namespace. It looks throughout all functions in a `.metallib` file.

2. `METAL_FUNC` is something like `inline`. It is not needed.

3. You can put these function in a `.h` file like `MTIShaderLib.h`. I think `METAL_FUNC` prefix is a little better, because Apple is using it. See header files in your Xcode: `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/lib/clang/902.1/include/metal`
