### ISSUE TITLE
Changing sampler for TransformFilter not working

### ISSUE THREAD

**Issue by d1xlord** [MetalPetal/MetalPetal#83]
Hi, I am scaling my image using the TransformFilter and want to set the Sampler AddressMode to ClampToEdge. I am changing the samplerDescriptor when providing the inputImage to the TransformFilter but the output still has black bars when the scaleValue is less than 1. I have tried digging inside the MTITransformFilter code to see if there was any additional filter which was causing the revert back to the default-SamplerDescriptor but found none. What's the issue here?

```
CGAffineTransform transform = CGAffineTransformMakeScale(imageRatio, imageRatio);
MTITransformFilter *transformFilter = [[MTITransformFilter alloc] init];
transformFilter.inputImage = [self.inputImage imageWithSamplerDescriptor:[MTISamplerDescriptor defaultSamplerDescriptorWithAddressMode:MTLSamplerAddressModeClampToEdge]];
transformFilter.transform = CATransform3DMakeAffineTransform(transform);
MTIImage *outputImage = transformFilter.outputImage;
```

**Comment by YuAo** [comment]
To grain the best performance possible, all transform filters (MTICropFilter, MTITransformFilter) in MetalPetal only draw the transformed area of the canvas. So this is not a sampler problem because the pixels outside the image is not even sampled. 

If you'd like to have the clamp to edge behavior, you may need to write a custom filter.
