### ISSUE TITLE
Code optimization question

### ISSUE THREAD

**Issue by alyfreym** [MetalPetal/MetalPetal#88]
Hi, I am writing my filter. In this filter, I need to impose a texture and apply a horizontal blur. Which option is faster and better than 1 - I will have two filters, the first one will add texture, the second one will apply blur, each filter will have a separate shader code. 2 - I will do it all in one filter, all operations will be processed by one shader code. I assume 2 second option is the best. But I'm not exactly sure, because the library is built so that you can build a chain of filters, or does it not matter?  thanks for the answer.

**Comment by YuAo** [comment]
In general, the second one is better. Using the second approach you only need to using one command encoder instead of two, and it uses less memory bandwidth (assuming on iOS devices here). So if you can do what you need to do in one filter, please do that.

However, I'm not sure about your approach here:

Assuming you need to first process the pixels using function "A", then do a horizontal blur.  For every pixel you need to blur, you'll need to sample neighborhood pixels, for example your blur radius is 11 pixels, you need to sample 10 neighborhood pixels, that means if you try to do all the things in one filter, you'll need to apply function "A" 10 times per pixel, right?

If you separate the process to two filter, you only need to apply function "A" once per pixel in the first filter then use the first filter's output to do the blur.

I think you may need to profile your program to decide which one is better.
