### ISSUE TITLE
Does MTISCNSceneRenderer or MTIImageView support multiple sample?

### ISSUE THREAD

**Issue by evanxlh** [MetalPetal/MetalPetal#93]
Hi @YuAo ,  If use the SCNView, it can set antialiasing mode, so for MTISCNSceneRenderer or MTIImageView, how to make them support multiple sample?  Many thanks!

**Comment by YuAo** [comment]
This feature is currently unavailable. I'll see what we can do.

**Comment by YuAo** [comment]
Unfortunately, after some investigation, I found that the `SCNView` uses a private API of `SCNRenderer` to support multiple sample. It calls a private method `- (void)set_antialiasingMode:` on `SCNRenderer` to enable the multiple sample support. 

That means we are impossible to do the same because it requires the use of private API.

It seems that we cannot implement this feature on our own as well, because the scene is rendered by SceneKit, the only way to enable the multisample support is to modify the SceneKit's internal render pipeline.

The suggestion is to [file a radar](https://developer.apple.com/bug-reporting/), tell Apple that you need multisample support for `SCNRenderer`, why you need that, and how it will improve your product. Hopefully they will add this feature in a future release.

**Comment by evanxlh** [comment]
@YuAo Thank you very much.

**Comment by alyfreym** [comment]
> @YuAo Thank you very much.

https://developer.apple.com/documentation/scenekit/scnrenderer/1641767-snapshotattime?language=objc not working ?  - SCNAntialiasingMode constants

**Comment by YuAo** [comment]
Hi, @evanxlh I found that it is possible to enable multisample anti-aliasing with the `SCNRenderer`. `SCNRenderer` is smart enough to implicitly enable the multisample support if the render pass descriptor contains a multisample color attachment.

I'll update MetalPetal later to add the MSAA support for `MTISCNSceneRenderer`.

**Comment by YuAo** [comment]
Done 4b79e0f60273e3d55d5b939199b80d0515df10ee

**Comment by GregOriol** [comment]
A little note if someone stumbles on this in the future: setting `sceneRenderer.antialiasingMode = .multisampling4X` does work well, except if `self.sceneRenderer.scnRenderer.showsStatistics` is set to `true`, then the renderer doesn't render anything (tested on iOS 18). When showsStatistics is enabled, only `antialiasingMode = .none` allows the renderer to render something... I hope this note helps someone not loose hours of debugging
